apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- ../../base
- route.yaml
patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: bgd
      namespace: demo
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: red
