apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- ../../base
#- demo-ns.yaml
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: bgd
      namespace: demo
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer